version: '3.8'

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile  
    volumes:
      - .:/app  
    ports:
      - "5000:5000"  
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}  
      # OAuth credentials
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db  

  db:
    image: postgres:latest  
    restart: always
    environment:
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: db_name  
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data:  
